-- MySQL Script generated by MySQL Workbench
-- Sun Aug  9 23:12:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS hotel;

CREATE DATABASE hotel;

USE hotel;

-- -----------------------------------------------------
-- Table `mydb`.`Guest`
-- -----------------------------------------------------
CREATE TABLE Guest (
  idGuest INT AUTO_INCREMENT,
  nameOfGuest VARCHAR(45) NOT NULL,
  address VARCHAR(45) NOT NULL,
  city VARCHAR(45) NOT NULL,
  state VARCHAR(45) NOT NULL,
  zip VARCHAR(45) NOT NULL,
  phoneNumber VARCHAR(45) NOT NULL,
  CONSTRAINT idGuest
	PRIMARY KEY (idGuest))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE Reservation (
  idReservation INT AUTO_INCREMENT NOT NULL,
  Guest_idGuest INT NOT NULL,
  adult INT NOT NULL,
  children INT NOT NULL,
  startDate DATE NOT NULL,
  endDate DATE NOT NULL,
  totalPrice  DECIMAL(4,2) NOT NULL,
  CONSTRAINT  idReservation
	PRIMARY KEY (idReservation),
  INDEX fk_Reservation_Guest_idx (Guest_idGuest ASC) VISIBLE,
  CONSTRAINT fk_Reservation_Guest
    FOREIGN KEY (Guest_idGuest)
    REFERENCES Guest (idGuest)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RoomType`
-- -----------------------------------------------------
CREATE TABLE RoomType (
  idRoomType INT AUTO_INCREMENT NOT NULL,
  roomtype VARCHAR(45) NOT NULL,
  CONSTRAINT idRoomType
	PRIMARY KEY (idRoomType))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE Room (
  idRoom INT NOT NULL,
  RoomType_idRoomType INT NOT NULL,
  ADAaccesible VARCHAR(45) NOT NULL,
  standardOccupancy INT NOT NULL,
  maxOccupancy INT NOT NULL,
  basePrice DECIMAL(4,2) NOT NULL,
  extraPerson DECIMAL(4,2) NULL,
  CONSTRAINT idRoom
	PRIMARY KEY (idRoom),
  INDEX fk_Room_RoomType1_idx (RoomType_idRoomType ASC) VISIBLE,
  CONSTRAINT fk_Room_RoomType1
    FOREIGN KEY (RoomType_idRoomType)
    REFERENCES RoomType (idRoomType)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room_has_Reservation`
-- -----------------------------------------------------
CREATE TABLE Room_has_Reservation (
  Reservation_idReservation INT NOT NULL,
  Room_idRoom INT NOT NULL,
  PRIMARY KEY (Room_idRoom, Reservation_idReservation),
  INDEX fk_Room_has_Reservation_Reservation1_idx (Reservation_idReservation ASC) VISIBLE,
  INDEX fk_Room_has_Reservation_Room1_idx (Room_idRoom ASC) VISIBLE,
  CONSTRAINT fk_Room_has_Reservation_Room1
    FOREIGN KEY (Room_idRoom)
    REFERENCES Room (idRoom)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Room_has_Reservation_Reservation1
    FOREIGN KEY (Reservation_idReservation )
    REFERENCES Reservation (idReservation)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ameneties`
-- -----------------------------------------------------
CREATE TABLE Ameneties (
  idAmeneties INT NOT NULL,
  amenetyType VARCHAR(45) NOT NULL,
  PRIMARY KEY (idAmeneties))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ameneties_has_Room`
-- -----------------------------------------------------
CREATE TABLE Ameneties_has_Room (
  Ameneties_idAmeneties INT NOT NULL,
  Room_idRoom INT NOT NULL,
  PRIMARY KEY (Ameneties_idAmeneties, Room_idRoom),
  INDEX fk_Ameneties_has_Room_Room1_idx (Room_idRoom ASC) VISIBLE,
  INDEX fk_Ameneties_has_Room_Ameneties1_idx (`Ameneties_idAmeneties` ASC) VISIBLE,
  CONSTRAINT fk_Ameneties_has_Room_Ameneties1
    FOREIGN KEY (Ameneties_idAmeneties)
    REFERENCES Ameneties (idAmeneties)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Ameneties_has_Room_Room1
    FOREIGN KEY (Room_idRoom)
    REFERENCES Room (idRoom)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
